<a href="https://colab.research.google.com/github/ricardokendy/name_columns/blob/main/name_columns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def name_columns(df):
  """
  Esta função permite padronizar todos os nomes das colunas de um dataframe, removendo as strings de espaços e pontos. Além de adicionar ou não o _
  df: dataframe que será alterado os nomes das colunas
  return: dataframe corrigido
  Autor: Ricardo Kendy Nakazone
  Versão 1.0
  """
  import pandas as pd
  resp = int(input('Do you prefer 1-(Avg_Area_Income) or 2-(AvgAreaIncome), answer only number: '))
  if resp == 1:
    for k in df.columns:
      word = ""
      word2 = ''
      word3 = ''
      cont = 0
      letter = ''
      for i in k:
        if i == ' ' or i =='.' or i=='-':
          word2 += '_'
        else:
          word2+=i
      word = ''
      for i in word2:
        word+=i
        cont+=1
        if letter =='_' and i == '_':
          for i in range(0,len(word)-1):
            word3 += word[i]
          word = word3
        letter = i
      df = df.rename(columns={k:word})

  elif resp==2:
    for k in df.columns:
      word = ""
      word2 = ''
      word3 = ''
      cont = 0
      letter = ''
      for i in k:
        if i == ' ' or i =='.' or i=='-':
          word2 += '_'
        else:
          word2+=i
      word = ''
      for i in word2:
        word+=i
        cont+=1
        if letter =='_' and i == '_':
          for i in range(0,len(word)-1):
            word3 += word[i]
          word = word3
        letter = i

      word2 = word
      word3 =''
      for i in word2:
        if i !='_':
          word3 += i
      df = df.rename(columns={k:word3})

  return df

In [ ]:
df = pd.read_csv('/content/USA_Housing.csv')

In [ ]:
df.head()

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [ ]:
df_correct = name_columns(df)
df_correct.columns

Do you prefer 1-(Avg_Area_Income) or 2-(AvgAreaIncome), answer only number: 1

Index(['Avg_Area_Income', 'Avg_Area_House_Age', 'Avg_Area_Number_of_Rooms',
       'Avg_Area_Number_of_Bedrooms', 'Area_Population', 'Price', 'Address'],
      dtype='object')

In [ ]:
df_correct.head()

,Avg_Area_Income,Avg_Area_House_Age,Avg_Area_Number_of_Rooms,Avg_Area_Number_of_Bedrooms,Area_Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386

In [ ]:
df_correct = name_columns(df)
df_correct.columns

Do you prefer 1-(Avg_Area_Income) or 2-(AvgAreaIncome), answer only number: 2

Index(['AvgAreaIncome', 'AvgAreaHouseAge', 'AvgAreaNumberofRooms',
       'AvgAreaNumberofBedrooms', 'AreaPopulation', 'Price', 'Address'],
      dtype='object')

In [ ]:
df_correct.head()

,AvgAreaIncome,AvgAreaHouseAge,AvgAreaNumberofRooms,AvgAreaNumberofBedrooms,AreaPopulation,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386